refs = {
    "how to change youtube privacy settings": "youtube private channel",
    "how to change snapchat privacy settings": "who can see my snapchat story",
    "how to change twitter privacy settings": "private twitter account",
    "how to search without being tracked": "most private browser",
    "how to browse without being tracked": "most private browser",
    "how to search anonymously": "best anonymous browser",
    "how to delete instagram": "delete account instagram",
    "how to encrypt phone calls": "encrypted phone calls",
    "how to encrypt text messages": "best private messaging app",
    "how to encrypt google hangouts": "google hangouts privacy",
    "how to encrypt skype": "skype privacy policy",
    "how to encrypt whatsapp": "whatsapp security settings",
    "how to protect against email monitoring": "how to protect against phishing",
    "how to protect against phone call monitoring": "delete hangout history",
    "how to protect against text message monitoring": "can someone read my text messages from their phone",
    "how to protect against google hangout monitoring": "google hangouts privacy",
    "how to protect against whatsapp monitoring": "how to encrypt whatsapp messages",
    "how to protect against skype monitoring": "skype privacy policy",
    "info handled appropriately facebook": "Facebook privacy policy",
    "info handled appropriately gmail": "gmail privacy issues",
    "info handled appropriately instagram": "instagram privacy policy",
    "info handled appropriately pokemongo": "Privacy policy Pokemon Go",
    "info handled appropriately twitter": "Twitter privacy policy",
    "info handled appropriately uber": "uber privacy policy",
    "hide facebook from government": "Facebook Privacy settings",
    "hide gmail from government": "Gmail privacy",
    "hide instagram from government": "private instagram posts",
    "hide pokemongo from government": "pokemon go settings",
    "hide twitter from government": "How to make tweets private",
    "hide uber from government": "Uber privacy",
    "hide youtube from government": "Youtube Privacy",
    "privacy policy facebook": "facebook app privacy policy",
    "privacy policy gmail": "gmail privacy policy",
    "privacy policy instagram": "instagram privacy policy",
    "privacy policy twitter": "twitter privacy policy",
    "remove social media connection facebook": "facebook delete friends",
    "remove social media connection instagram": "how to unfollow on Instagram",
    "remove social media connection snapchat": "remove snapchat friends",
    "remove social media connection twitter": "how to unfollow on twitter",
    "tool to encrypt email": "how to encrypt emails",
    "tool to encrypt google hangouts": "google hangouts encryption",
    "tool to encrypt phone calls": "Encrypt phone calls",
    "tool to encrypt skype": "skype encryption",
    "tool to encrypt text messages": "how to encrypt text messages",
    "tool to encrypt whatsapp": "how to encrypt whatsapp",
}
