refs = {
    "how to change youtube privacy settings": "youtube private channel",
    "how to change snapchat privacy settings": "who can see my snapchat story",
    "how to change twitter privacy settings": "private twitter account",
    "how to search without being tracked": "most private browser",
    "how to browse without being tracked": "most private browser",
    "how to search anonymously": "best anonymous browser",
    "how to delete instagram": "delete account instagram",
    "how to encrypt phone calls": "encrypted phone calls",
    "how to encrypt text messages": "best private messaging app",
    "how to encrypt google hangouts": "google hangouts privacy",
    "how to encrypt skype": "skype privacy policy",
    "how to encrypt whatsapp": "whatsapp security settings",
    "how to protect against email monitoring": "how to protect against phishing",
    "how to protect against phone call monitoring": "delete hangout history",
    "how to protect against text message monitoring": "can someone read my text messages from their phone",
    "how to protect against google hangout monitoring": "google hangouts privacy",
    "how to protect against whatsapp monitoring": "how to encrypt whatsapp messages",
    "how to protect against skype monitoring": "skype privacy policy",
}
