refs = {
    "how to change facebook privacy settings": "how to change facebook privacy settings",
    "how to change youtube privacy settings": "youtube private channel",
    "how to change snapchat privacy settings": "who can see my snapchat story",
    "how to change instagram privacy settings": "how to change instagram privacy settings",
    "how to change twitter privacy settings": "private twitter account",
    "how to search without being tracked": "most private browser",
    "how to browse without being tracked": "most private browser",
    "how to search anonymously": "best anonymous browser",
    "how to browse anonymously": "how to browse anonymously",
    "search without history": "search without history",
    "how to delete a facebook account": "how to delete a facebook account",
    "how to delete a youtube account": "how to delete a youtube account",
    "how to delete a snapchat account": "how to delete a snapchat account",
    "how to delete a instagram account": "how to delete a instagram account",
    "how to delete a google account": "how to delete a google account",
    "how to delete a twitter account": "how to delete a twitter account",
    "government monitoring social media": "government monitoring social media",
    "how to delete facebook": "how to delete facebook",
    "how to delete gmail": "how to delete gmail",
    "how to delete twitter": "how to delete twitter",
    "how to delete youtube": "how to delete youtube",
    "how to delete snapchat": "how to delete snapchat",
    "how to delete instagram": "delete account instagram",
    "how to delete pokemongo": "how to delete pokemongo",
    "how to uninstall facebook": "how to uninstall facebook",
    "how to uninstall gmail": "how to uninstall gmail",
    "how to uninstall twitter": "how to uninstall twitter",
    "how to uninstall youtube": "how to uninstall youtube",
    "how to uninstall snapchat": "how to uninstall snapchat",
    "how to uninstall instagram": "how to uninstall instagram",
    "how to uninstall pokemongo": "how to uninstall pokemongo",
    "how to unfollow someone on facebook": "how to unfollow someone on facebook",
    "how to unfollow someone on twitter": "how to unfollow someone on twitter",
    "how to unfollow someone on snapchat": "how to unfollow someone on snapchat",
    "how to unfollow someone on instagram": "how to unfollow someone on instagram",
    "how to unfriend someone on facebook": "how to unfriend someone on facebook",
    "how to unfriend someone on twitter": "how to unfriend someone on twitter",
    "how to unfriend someone on snapchat": "how to unfriend someone on snapchat",
    "how to unfriend someone on instagram": "how to unfriend someone on instagram",
    "how to encrypt emails": "how to encrypt emails",
    "how to encrypt phone calls": "encrypted phone calls",
    "how to encrypt text messages": "best private messaging app",
    "how to encrypt google hangouts": "google hangouts privacy",
    "how to encrypt skype": "skype privacy policy",
    "how to encrypt whatsapp": "whatsapp security settings",
    "how to protect against email monitoring": "how to protect against phishing",
    "how to protect against phone call monitoring": "delete hangout history",
    "how to protect against text message monitoring": "can someone read my text messages from their phone",
    "how to protect against google hangout monitoring": "google hangouts privacy",
    "how to protect against whatsapp monitoring": "how to encrypt whatsapp messages",
    "how to protect against skype monitoring": "skype privacy policy",
}
